import crypto from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import fsp from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import path from "node:path";

import { CABINET_INTERNAL_DIR } from "@/lib/storage/path-utils";

export const CLI_PROXY_VERSION = "7.2.77";
const RELEASE_BASE = `https://github.com/router-for-me/CLIProxyAPI/releases/download/v${CLI_PROXY_VERSION}`;

type SupportedPlatform = "darwin" | "linux" | "win32";
type SupportedArch = "x64" | "arm64";

interface ReleaseAsset {
  name: string;
  sha256: string;
  archive: "tar.gz" | "zip";
}

const RELEASE_ASSETS: Record<`${SupportedPlatform}-${SupportedArch}`, ReleaseAsset> = {
  "darwin-arm64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_darwin_aarch64.tar.gz`,
    sha256: "a7c265f86895bb9d946ad28e3a126a502096dc91afb7e9838477aa4d39e84554",
    archive: "tar.gz",
  },
  "darwin-x64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_darwin_amd64.tar.gz`,
    sha256: "6ff8fad7afaaf0f952d24ac9fb1df790eab62a64ea90981386cbbbdfbc3e9c37",
    archive: "tar.gz",
  },
  "linux-arm64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_linux_aarch64_no-plugin.tar.gz`,
    sha256: "1c87f253d44b6ce18d7bc1c8717bf0c9fbf3c056d543cff2e9a7665416b81f14",
    archive: "tar.gz",
  },
  "linux-x64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_linux_amd64_no-plugin.tar.gz`,
    sha256: "32a7929269baa31e75c6457420cb6178c7293b7ba4e1fdcee2097a7949dc6b52",
    archive: "tar.gz",
  },
  "win32-arm64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_windows_aarch64.zip`,
    sha256: "cbef6ab244741a41ad9d278716bf37cac7a233b80063d22254df04132e0c39cc",
    archive: "zip",
  },
  "win32-x64": {
    name: `CLIProxyAPI_${CLI_PROXY_VERSION}_windows_amd64.zip`,
    sha256: "daa8277af35e2a5c7bbc9a71e768dceed5bdb31e66d48ac36be63b3d52338d1d",
    archive: "zip",
  },
};

export interface CLIProxyPaths {
  root: string;
  binaryDir: string;
  binaryPath: string;
  authDir: string;
  configPath: string;
  runtimePath: string;
  installManifestPath: string;
  licensePath: string;
}

export interface RuntimeSecrets {
  version: 1;
  port: number;
  apiKey: string;
  managementKey: string;
  routingEnabled: boolean;
  autoStart: boolean;
}

export interface CLIProxyStatus {
  supported: boolean;
  installed: boolean;
  running: boolean;
  version: string;
  port: number | null;
  pid: number | null;
  routingEnabled: boolean;
  error?: string;
}

export interface CLIProxyConnection {
  baseUrl: string;
  apiKey: string;
}

export interface CLIProxyOAuthStart {
  status: string;
  url: string;
  state: string;
  flow?: string;
  user_code?: string;
  expires_in?: number;
}

export interface CLIProxyAccountSummary {
  provider: string;
  label: string | null;
  email: string | null;
  status: string | null;
  disabled: boolean;
  unavailable: boolean;
}

const OAUTH_ENDPOINTS = {
  anthropic: "anthropic-auth-url",
  codex: "codex-auth-url",
  antigravity: "antigravity-auth-url",
  xai: "xai-auth-url",
  kimi: "kimi-auth-url",
} as const;

export type CLIProxyOAuthProvider = keyof typeof OAUTH_ENDPOINTS;

export function resolveCLIProxyAsset(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch
): ReleaseAsset {
  if (!(["darwin", "linux", "win32"] as string[]).includes(platform)) {
    throw new Error(`CLIProxyAPI is not supported on ${platform}.`);
  }
  if (arch !== "x64" && arch !== "arm64") {
    throw new Error(`CLIProxyAPI is not supported on ${platform}/${arch}.`);
  }
  return RELEASE_ASSETS[`${platform as SupportedPlatform}-${arch}`];
}

export function getCLIProxyPaths(root = path.join(CABINET_INTERNAL_DIR, "cli-proxy")): CLIProxyPaths {
  const binaryDir = path.join(root, "bin", CLI_PROXY_VERSION);
  return {
    root,
    binaryDir,
    binaryPath: path.join(binaryDir, process.platform === "win32" ? "cli-proxy-api.exe" : "cli-proxy-api"),
    authDir: path.join(root, "auth"),
    configPath: path.join(root, "config.yaml"),
    runtimePath: path.join(root, "runtime.json"),
    installManifestPath: path.join(binaryDir, "install.json"),
    licensePath: path.join(binaryDir, "LICENSE"),
  };
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function renderCLIProxyConfig(paths: CLIProxyPaths, runtime: RuntimeSecrets): string {
  return [
    '# Generated by Cabinet. Change connector settings in Cabinet, not this file.',
    'host: "127.0.0.1"',
    `port: ${runtime.port}`,
    `auth-dir: ${yamlString(paths.authDir)}`,
    'api-keys:',
    `  - ${yamlString(runtime.apiKey)}`,
    'remote-management:',
    '  allow-remote: false',
    `  secret-key: ${yamlString(runtime.managementKey)}`,
    '  disable-control-panel: true',
    'plugins:',
    '  enabled: false',
    'debug: false',
    'logging-to-file: false',
    'usage-statistics-enabled: false',
    'ws-auth: true',
    'pprof:',
    '  enable: false',
    'routing:',
    '  strategy: "round-robin"',
    '  session-affinity: true',
    '  session-affinity-ttl: "1h"',
    '',
  ].join('\n');
}

async function writePrivateFile(filePath: string, contents: string): Promise<void> {
  await fsp.mkdir(path.dirname(filePath), { recursive: true, mode: 0o700 });
  const temporary = `${filePath}.${process.pid}.${crypto.randomBytes(6).toString("hex")}.tmp`;
  await fsp.writeFile(temporary, contents, { encoding: "utf8", mode: 0o600 });
  await fsp.rename(temporary, filePath);
  await fsp.chmod(filePath, 0o600).catch(() => {});
}

async function sha256File(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const stream = fs.createReadStream(filePath);
    stream.on("error", reject);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("end", () => resolve(hash.digest("hex")));
  });
}

async function run(command: string, args: string[]): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { stdio: ["ignore", "pipe", "pipe"] });
    let stderr = "";
    child.stderr.on("data", (chunk) => {
      stderr += String(chunk);
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} exited with ${code}: ${stderr.trim()}`));
    });
  });
}

async function download(url: string, target: string): Promise<void> {
  const response = await fetch(url, {
    headers: { "User-Agent": `Cabinet/${CLI_PROXY_VERSION}` },
    redirect: "follow",
    signal: AbortSignal.timeout(120_000),
  });
  if (!response.ok || !response.body) {
    throw new Error(`CLIProxyAPI download failed (${response.status}).`);
  }
  const bytes = Buffer.from(await response.arrayBuffer());
  await fsp.writeFile(target, bytes, { mode: 0o600 });
}

async function extract(asset: ReleaseAsset, archivePath: string, targetDir: string): Promise<void> {
  if (asset.archive === "tar.gz") {
    await run("tar", ["-xzf", archivePath, "-C", targetDir]);
    return;
  }
  await run("powershell.exe", [
    "-NoProfile",
    "-NonInteractive",
    "-Command",
    "Expand-Archive -LiteralPath $args[0] -DestinationPath $args[1] -Force",
    archivePath,
    targetDir,
  ]);
}

async function freeLoopbackPort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (!address || typeof address === "string") {
        server.close();
        reject(new Error("Could not allocate a CLIProxyAPI port."));
        return;
      }
      server.close((error) => (error ? reject(error) : resolve(address.port)));
    });
  });
}

export function buildCLIProxyProcessEnv(
  source: Record<string, string | undefined> = process.env
): NodeJS.ProcessEnv {
  const allowed = [
    "NODE_ENV",
    "PATH", "HOME", "USERPROFILE", "TMPDIR", "TEMP", "TMP",
    "SYSTEMROOT", "WINDIR", "COMSPEC", "LANG", "LC_ALL",
    "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY",
    "http_proxy", "https_proxy", "no_proxy",
    "SSL_CERT_FILE", "SSL_CERT_DIR",
  ];
  return Object.fromEntries(
    allowed.flatMap((key) => typeof source[key] === "string" ? [[key, source[key]]] : [])
  ) as NodeJS.ProcessEnv;
}

async function readRuntime(paths: CLIProxyPaths): Promise<RuntimeSecrets | null> {
  try {
    const parsed = JSON.parse(await fsp.readFile(paths.runtimePath, "utf8")) as Partial<RuntimeSecrets>;
    if (
      parsed.version !== 1 ||
      typeof parsed.port !== "number" ||
      typeof parsed.apiKey !== "string" ||
      typeof parsed.managementKey !== "string"
    ) return null;
    return parsed as RuntimeSecrets;
  } catch {
    return null;
  }
}

function readRuntimeSync(paths: CLIProxyPaths): RuntimeSecrets | null {
  try {
    const parsed = JSON.parse(fs.readFileSync(paths.runtimePath, "utf8")) as Partial<RuntimeSecrets>;
    if (
      parsed.version !== 1 ||
      typeof parsed.port !== "number" ||
      typeof parsed.apiKey !== "string" ||
      typeof parsed.managementKey !== "string"
    ) return null;
    return {
      ...parsed,
      routingEnabled: parsed.routingEnabled === true,
      autoStart: parsed.autoStart !== false,
    } as RuntimeSecrets;
  } catch {
    return null;
  }
}

function maskAccountIdentity(value: string | null): string | null {
  if (!value) return null;
  const at = value.indexOf("@");
  if (at > 0) return `${value[0]}***${value.slice(at)}`;
  return value.length <= 2 ? "••" : `${value.slice(0, 2)}•••`;
}

export function validateCLIProxyOAuthStart(value: unknown): CLIProxyOAuthStart {
  if (!value || typeof value !== "object") throw new Error("CLIProxyAPI returned an invalid OAuth response.");
  const input = value as Record<string, unknown>;
  if (typeof input.url !== "string" || input.url.length > 4096) {
    throw new Error("CLIProxyAPI returned an invalid OAuth URL.");
  }
  let url: URL;
  try {
    url = new URL(input.url);
  } catch {
    throw new Error("CLIProxyAPI returned an invalid OAuth URL.");
  }
  if (url.protocol !== "https:" || url.username || url.password) {
    throw new Error("CLIProxyAPI returned an unsafe OAuth URL.");
  }
  if (typeof input.state !== "string" || !/^[A-Za-z0-9._~-]{1,256}$/.test(input.state)) {
    throw new Error("CLIProxyAPI returned an invalid OAuth state.");
  }
  return {
    status: typeof input.status === "string" ? input.status.slice(0, 64) : "ok",
    url: url.toString(),
    state: input.state,
    ...(typeof input.flow === "string" ? { flow: input.flow.slice(0, 64) } : {}),
    ...(typeof input.user_code === "string" ? { user_code: input.user_code.slice(0, 256) } : {}),
    ...(typeof input.expires_in === "number" && Number.isFinite(input.expires_in)
      ? { expires_in: Math.max(0, Math.min(input.expires_in, 86_400)) }
      : {}),
  };
}

function validateOAuthState(state: string): string {
  const value = state.trim();
  if (!/^[A-Za-z0-9._~-]{1,256}$/.test(value)) throw new Error("Invalid OAuth state.");
  return value;
}

async function createRuntime(paths: CLIProxyPaths): Promise<RuntimeSecrets> {
  const previous = await readRuntime(paths);
  const runtime: RuntimeSecrets = {
    version: 1,
    port: await freeLoopbackPort(),
    apiKey: previous?.apiKey || crypto.randomBytes(32).toString("hex"),
    managementKey: previous?.managementKey || crypto.randomBytes(32).toString("hex"),
    routingEnabled: previous?.routingEnabled === true,
    autoStart: previous?.autoStart !== false,
  };
  await fsp.mkdir(paths.authDir, { recursive: true, mode: 0o700 });
  await fsp.chmod(paths.authDir, 0o700).catch(() => {});
  await writePrivateFile(paths.runtimePath, `${JSON.stringify(runtime, null, 2)}\n`);
  await writePrivateFile(paths.configPath, renderCLIProxyConfig(paths, runtime));
  return runtime;
}

export class CLIProxyRuntime {
  private readonly paths: CLIProxyPaths;
  private child: ChildProcess | null = null;
  private runtime: RuntimeSecrets | null = null;
  private lastError: string | undefined;
  private connectedProviders = new Set<string>();
  private lifecycleQueue: Promise<void> = Promise.resolve();
  private shuttingDown = false;

  constructor(root?: string) {
    this.paths = getCLIProxyPaths(root);
  }

  private serialize<T>(operation: () => Promise<T>): Promise<T> {
    const result = this.lifecycleQueue.then(operation, operation);
    this.lifecycleQueue = result.then(() => {}, () => {});
    return result;
  }

  async install(): Promise<void> {
    return this.serialize(() => this.installInner());
  }

  private async installInner(): Promise<void> {
    const asset = resolveCLIProxyAsset();
    if (await this.verifyInstalledBinary(asset)) return;
    await fsp.mkdir(path.dirname(this.paths.binaryDir), { recursive: true, mode: 0o700 });
    const temporaryRoot = await fsp.mkdtemp(path.join(os.tmpdir(), "cabinet-cli-proxy-"));
    const archivePath = path.join(temporaryRoot, asset.name);
    const extractDir = path.join(temporaryRoot, "extract");
    await fsp.mkdir(extractDir);
    try {
      await download(`${RELEASE_BASE}/${asset.name}`, archivePath);
      const digest = await sha256File(archivePath);
      if (!crypto.timingSafeEqual(Buffer.from(digest), Buffer.from(asset.sha256))) {
        throw new Error("CLIProxyAPI checksum verification failed; the download was discarded.");
      }
      await extract(asset, archivePath, extractDir);
      const extractedBinary = path.join(
        extractDir,
        process.platform === "win32" ? "cli-proxy-api.exe" : "cli-proxy-api"
      );
      if (!fs.existsSync(extractedBinary)) {
        throw new Error("CLIProxyAPI archive did not contain the expected binary.");
      }
      await fsp.rm(this.paths.binaryDir, { recursive: true, force: true });
      await fsp.mkdir(this.paths.binaryDir, { recursive: true, mode: 0o700 });
      await fsp.copyFile(extractedBinary, this.paths.binaryPath);
      if (process.platform !== "win32") await fsp.chmod(this.paths.binaryPath, 0o700);
      const extractedLicense = path.join(extractDir, "LICENSE");
      if (fs.existsSync(extractedLicense)) {
        await fsp.copyFile(extractedLicense, this.paths.licensePath);
      }
      const binarySha256 = await sha256File(this.paths.binaryPath);
      await writePrivateFile(
        this.paths.installManifestPath,
        `${JSON.stringify({
          version: CLI_PROXY_VERSION,
          asset: asset.name,
          archiveSha256: asset.sha256,
          binarySha256,
        }, null, 2)}\n`
      );
    } finally {
      await fsp.rm(temporaryRoot, { recursive: true, force: true }).catch(() => {});
    }
  }

  private async verifyInstalledBinary(asset = resolveCLIProxyAsset()): Promise<boolean> {
    if (!fs.existsSync(this.paths.binaryPath)) return false;
    try {
      const manifest = JSON.parse(
        await fsp.readFile(this.paths.installManifestPath, "utf8")
      ) as Record<string, unknown>;
      if (
        manifest.version !== CLI_PROXY_VERSION ||
        manifest.asset !== asset.name ||
        manifest.archiveSha256 !== asset.sha256 ||
        typeof manifest.binarySha256 !== "string"
      ) return false;
      return (await sha256File(this.paths.binaryPath)) === manifest.binarySha256;
    } catch {
      return false;
    }
  }

  async start(): Promise<CLIProxyStatus> {
    return this.serialize(() => this.startInner());
  }

  private async startInner(): Promise<CLIProxyStatus> {
    if (this.shuttingDown) throw new Error("Cabinet is shutting down.");
    if (this.child && this.child.exitCode === null && !this.child.killed) return this.status();
    if (!(await this.verifyInstalledBinary())) {
      throw new Error("CLIProxyAPI is not installed or failed its integrity check.");
    }

    this.runtime = await createRuntime(this.paths);
    if (this.shuttingDown) throw new Error("Cabinet is shutting down.");
    this.runtime.autoStart = true;
    await writePrivateFile(this.paths.runtimePath, `${JSON.stringify(this.runtime, null, 2)}\n`);
    this.lastError = undefined;
    this.connectedProviders.clear();
    const child = spawn(this.paths.binaryPath, ["-config", this.paths.configPath], {
      cwd: this.paths.root,
      env: buildCLIProxyProcessEnv(),
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    this.child = child;

    let stderr = "";
    // Always drain both pipes. CLIProxyAPI emits startup/request diagnostics;
    // leaving stdout unread can fill the OS pipe buffer and stall the proxy.
    child.stdout?.on("data", () => {});
    child.stderr?.on("data", (chunk) => {
      stderr = `${stderr}${String(chunk)}`.slice(-8_000);
    });
    child.once("error", (error) => {
      this.lastError = error.message;
    });
    child.once("exit", (code, signal) => {
      if (code !== 0 && signal !== "SIGTERM") {
        const detail = stderr.trim().slice(-2_000);
        if (detail) console.error(`[cli-proxy] sidecar exited: ${detail}`);
        this.lastError = "CLIProxyAPI exited unexpectedly. Check Cabinet daemon logs for details.";
      }
      if (this.child === child) this.child = null;
      this.connectedProviders.clear();
    });

    const deadline = Date.now() + 15_000;
    while (Date.now() < deadline) {
      if (child.exitCode !== null) break;
      try {
        const response = await fetch(`http://127.0.0.1:${this.runtime.port}/healthz`, {
          signal: AbortSignal.timeout(1_000),
        });
        if (response.ok) {
          await this.listAccounts().catch(() => []);
          return this.status();
        }
      } catch {
        // Process is still starting.
      }
      await new Promise((resolve) => setTimeout(resolve, 100));
    }

    this.stopSync();
    throw new Error(this.lastError || "CLIProxyAPI did not become ready within 15 seconds.");
  }

  async stop(): Promise<void> {
    return this.serialize(() => this.stopInner(true));
  }

  private async stopInner(disableAutoStart: boolean): Promise<void> {
    if (disableAutoStart) {
      const runtime = this.runtime || await readRuntime(this.paths);
      if (runtime) {
        runtime.autoStart = false;
        this.runtime = runtime;
        await writePrivateFile(this.paths.runtimePath, `${JSON.stringify(runtime, null, 2)}\n`);
      }
    }
    const child = this.child;
    if (!child || child.exitCode !== null) return;
    child.kill("SIGTERM");
    await Promise.race([
      new Promise<void>((resolve) => child.once("exit", () => resolve())),
      new Promise<void>((resolve) => setTimeout(resolve, 5_000)),
    ]);
    if (child.exitCode === null) child.kill("SIGKILL");
    if (this.child === child) this.child = null;
    this.connectedProviders.clear();
  }

  stopSync(): void {
    if (this.child && this.child.exitCode === null) this.child.kill("SIGTERM");
  }

  async stopForShutdown(): Promise<void> {
    this.shuttingDown = true;
    await Promise.race([
      this.lifecycleQueue,
      new Promise<void>((resolve) => setTimeout(resolve, 20_000)),
    ]);
    await this.stopInner(false);
  }

  async startConfigured(): Promise<CLIProxyStatus> {
    const persisted = await readRuntime(this.paths);
    if (!persisted?.autoStart) return this.status();
    if (!(await this.verifyInstalledBinary())) return this.status();
    return this.start();
  }

  status(): CLIProxyStatus {
    if (!this.runtime) this.runtime = readRuntimeSync(this.paths);
    let supported = true;
    let platformError: string | undefined;
    try {
      resolveCLIProxyAsset();
    } catch (error) {
      supported = false;
      platformError = error instanceof Error ? error.message : String(error);
    }
    return {
      supported,
      installed: fs.existsSync(this.paths.binaryPath),
      running: Boolean(this.child && this.child.exitCode === null && !this.child.killed),
      version: CLI_PROXY_VERSION,
      port: this.runtime?.port ?? null,
      pid: this.child?.pid ?? null,
      routingEnabled: this.runtime?.routingEnabled === true,
      ...(this.lastError || platformError ? { error: this.lastError || platformError } : {}),
    };
  }

  connection(provider?: "claude" | "codex", force = false): CLIProxyConnection | null {
    if (!this.runtime || !this.status().running) return null;
    if (!force) {
      if (!provider || !this.shouldRoute(provider)) return null;
    }
    return {
      baseUrl: `http://127.0.0.1:${this.runtime.port}`,
      apiKey: this.runtime.apiKey,
    };
  }

  shouldRoute(provider: "claude" | "codex"): boolean {
    if (!this.runtime) this.runtime = readRuntimeSync(this.paths);
    if (!this.runtime?.routingEnabled) return false;
    if (this.connectedProviders.has(provider)) return true;
    try {
      for (const entry of fs.readdirSync(this.paths.authDir, { withFileTypes: true })) {
        if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".json")) continue;
        const record = JSON.parse(
          fs.readFileSync(path.join(this.paths.authDir, entry.name), "utf8")
        ) as Record<string, unknown>;
        if (record.disabled === true || record.unavailable === true) continue;
        const type = String(record.type || record.provider || "").toLowerCase();
        if (type === provider || (provider === "claude" && type === "anthropic")) {
          this.connectedProviders.add(provider);
          return true;
        }
      }
    } catch {
      // Missing/unreadable auth state means no automatic routing decision.
    }
    return false;
  }

  private async request(pathname: string, init: RequestInit = {}): Promise<unknown> {
    if (!this.runtime || !this.status().running) throw new Error("CLIProxyAPI is not running.");
    const headers = new Headers(init.headers);
    headers.set("X-Management-Key", this.runtime.managementKey);
    const response = await fetch(`http://127.0.0.1:${this.runtime.port}${pathname}`, {
      ...init,
      headers,
      signal: init.signal || AbortSignal.timeout(35_000),
    });
    const text = await response.text();
    let body: unknown = text;
    try { body = JSON.parse(text); } catch {}
    if (!response.ok) {
      const message = body && typeof body === "object" && "error" in body
        ? String((body as { error: unknown }).error)
        : text || `HTTP ${response.status}`;
      throw new Error(message);
    }
    return body;
  }

  async startOAuth(provider: CLIProxyOAuthProvider): Promise<CLIProxyOAuthStart> {
    const endpoint = OAUTH_ENDPOINTS[provider];
    if (!endpoint) throw new Error(`Unsupported CLIProxyAPI OAuth provider: ${provider}`);
    return validateCLIProxyOAuthStart(
      await this.request(`/v0/management/${endpoint}?is_webui=1`)
    );
  }

  async oauthStatus(state: string): Promise<unknown> {
    return this.request(
      `/v0/management/get-auth-status?state=${encodeURIComponent(validateOAuthState(state))}`
    );
  }

  async cancelOAuth(state: string): Promise<unknown> {
    return this.request(`/v0/management/oauth-session?state=${encodeURIComponent(validateOAuthState(state))}`, {
      method: "DELETE",
    });
  }

  async listModels(): Promise<unknown> {
    if (!this.runtime || !this.status().running) throw new Error("CLIProxyAPI is not running.");
    const response = await fetch(`http://127.0.0.1:${this.runtime.port}/v1/models`, {
      headers: { Authorization: `Bearer ${this.runtime.apiKey}` },
      signal: AbortSignal.timeout(10_000),
    });
    if (!response.ok) throw new Error(`CLIProxyAPI model request failed (${response.status}).`);
    return response.json();
  }

  async listAccounts(): Promise<CLIProxyAccountSummary[]> {
    const response = await this.request("/v0/management/auth-files") as {
      files?: Array<Record<string, unknown>>;
    };
    const accounts = (response.files || []).map((entry) => ({
      provider: String(entry.provider || entry.type || "unknown").toLowerCase(),
      label: maskAccountIdentity(
        typeof entry.label === "string" && entry.label.trim() ? entry.label.trim() : null
      ),
      email: maskAccountIdentity(
        typeof entry.email === "string" && entry.email.trim() ? entry.email.trim() : null
      ),
      status: typeof entry.status === "string" && entry.status.trim() ? entry.status.trim() : null,
      disabled: entry.disabled === true,
      unavailable: entry.unavailable === true,
    }));
    this.connectedProviders = new Set(
      accounts
        .filter((account) => !account.disabled && !account.unavailable)
        .map((account) => account.provider === "anthropic" ? "claude" : account.provider)
    );
    return accounts;
  }

  async setRoutingEnabled(enabled: boolean): Promise<CLIProxyStatus> {
    return this.serialize(async () => {
      if (!this.runtime) this.runtime = await createRuntime(this.paths);
      this.runtime.routingEnabled = enabled;
      await writePrivateFile(this.paths.runtimePath, `${JSON.stringify(this.runtime, null, 2)}\n`);
      return this.status();
    });
  }
}

export const cliProxyRuntime = new CLIProxyRuntime();
