/**
 * Generates server/http/route-manifest.ts: a static-import manifest of every
 * Next route handler under src/app/api, mounted by the daemon's Express app.
 *
 * Static (not dynamic) imports are required so esbuild can bundle the daemon
 * for the Electron package (scripts/prepare-electron-package.mjs).
 *
 * Usage:
 *   npm run api:manifest         # (re)write the manifest
 *   npm run api:manifest:check   # exit 1 if the manifest is out of date
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  compareExpressPaths,
  extractMethods,
  routeFileToExpressPath,
} from "../server/http/manifest-lib";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const apiRoot = path.join(repoRoot, "src", "app", "api");
const outFile = path.join(repoRoot, "server", "http", "route-manifest.ts");

function findRouteFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...findRouteFiles(full));
    else if (entry.name === "route.ts") out.push(full);
  }
  return out;
}

const entries = findRouteFiles(apiRoot)
  .map((file) => {
    const relative = path.relative(repoRoot, file).replace(/\\/g, "/");
    return {
      relative,
      expressPath: routeFileToExpressPath(relative),
      methods: extractMethods(fs.readFileSync(file, "utf-8")),
    };
  })
  .filter((entry) => entry.methods.length > 0)
  .sort((a, b) => compareExpressPaths(a.expressPath, b.expressPath));

const imports = entries
  .map((entry, i) => `import * as r${i} from "../../${entry.relative.replace(/\.ts$/, "")}";`)
  .join("\n");

const rows = entries
  .map(
    (entry, i) =>
      `  { path: ${JSON.stringify(entry.expressPath)}, methods: ${JSON.stringify(entry.methods)}, module: r${i} },`
  )
  .join("\n");

const content = `// AUTO-GENERATED by scripts/generate-api-manifest.ts — do not edit by hand.
// Regenerate with: npm run api:manifest
/* eslint-disable */
${imports}

export const apiRoutes = [
${rows}
] as const;
`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf-8") : "";
  if (current !== content) {
    console.error("server/http/route-manifest.ts is out of date. Run: npm run api:manifest");
    process.exit(1);
  }
  console.log(`route-manifest.ts up to date (${entries.length} routes).`);
} else {
  fs.writeFileSync(outFile, content);
  console.log(`Wrote ${entries.length} routes to server/http/route-manifest.ts`);
}
