// AUTO-GENERATED by scripts/generate-api-manifest.ts — do not edit by hand.
// Regenerate with: npm run api:manifest
/* eslint-disable */
import * as r0 from "../../src/app/api/agents/route";
import * as r1 from "../../src/app/api/agents/auto-link/route";
import * as r2 from "../../src/app/api/agents/channels/route";
import * as r3 from "../../src/app/api/agents/claude-login/[action]/route";
import * as r4 from "../../src/app/api/agents/cli-proxy/[...action]/route";
import * as r5 from "../../src/app/api/agents/config/route";
import * as r6 from "../../src/app/api/agents/config/cabinet-env/route";
import * as r7 from "../../src/app/api/agents/config/cli-mcp-servers/route";
import * as r8 from "../../src/app/api/agents/config/integration-environments/route";
import * as r9 from "../../src/app/api/agents/config/integrations/route";
import * as r10 from "../../src/app/api/agents/config/mcp-catalog/route";
import * as r11 from "../../src/app/api/agents/config/mcp-catalog/connect/route";
import * as r12 from "../../src/app/api/agents/config/mcp-catalog/discord-check/route";
import * as r13 from "../../src/app/api/agents/config/mcp-catalog/microsoft/login/route";
import * as r14 from "../../src/app/api/agents/config/mcp-catalog/oauth/login/route";
import * as r15 from "../../src/app/api/agents/config/mcp-catalog/test/route";
import * as r16 from "../../src/app/api/agents/config/mcp-catalog/verify/route";
import * as r17 from "../../src/app/api/agents/config/notifications/test/route";
import * as r18 from "../../src/app/api/agents/conversations/route";
import * as r19 from "../../src/app/api/agents/conversations/events/route";
import * as r20 from "../../src/app/api/agents/conversations/[id]/route";
import * as r21 from "../../src/app/api/agents/conversations/[id]/actions/route";
import * as r22 from "../../src/app/api/agents/conversations/[id]/claude-transcript/route";
import * as r23 from "../../src/app/api/agents/conversations/[id]/compact/route";
import * as r24 from "../../src/app/api/agents/conversations/[id]/continue/route";
import * as r25 from "../../src/app/api/agents/conversations/[id]/diffs/route";
import * as r26 from "../../src/app/api/agents/conversations/[id]/events/route";
import * as r27 from "../../src/app/api/agents/conversations/[id]/events-log/route";
import * as r28 from "../../src/app/api/agents/digest/route";
import * as r29 from "../../src/app/api/agents/events/route";
import * as r30 from "../../src/app/api/agents/gallery/route";
import * as r31 from "../../src/app/api/agents/headless/route";
import * as r32 from "../../src/app/api/agents/import/route";
import * as r33 from "../../src/app/api/agents/inbox-drafts/route";
import * as r34 from "../../src/app/api/agents/library/route";
import * as r35 from "../../src/app/api/agents/library/[slug]/add/route";
import * as r36 from "../../src/app/api/agents/personas/route";
import * as r37 from "../../src/app/api/agents/personas/[slug]/route";
import * as r38 from "../../src/app/api/agents/personas/[slug]/avatar/route";
import * as r39 from "../../src/app/api/agents/personas/[slug]/export/route";
import * as r40 from "../../src/app/api/agents/personas/[slug]/workspace/route";
import * as r41 from "../../src/app/api/agents/providers/route";
import * as r42 from "../../src/app/api/agents/providers/status/route";
import * as r43 from "../../src/app/api/agents/providers/[id]/models/route";
import * as r44 from "../../src/app/api/agents/providers/[id]/verify/route";
import * as r45 from "../../src/app/api/agents/review/route";
import * as r46 from "../../src/app/api/agents/scheduler/route";
import * as r47 from "../../src/app/api/agents/skills/route";
import * as r48 from "../../src/app/api/agents/skills/catalog/route";
import * as r49 from "../../src/app/api/agents/skills/import/route";
import * as r50 from "../../src/app/api/agents/skills/scan/route";
import * as r51 from "../../src/app/api/agents/skills/[key]/route";
import * as r52 from "../../src/app/api/agents/skills/[key]/bundle-into-cabinet/route";
import * as r53 from "../../src/app/api/agents/tasks/route";
import * as r54 from "../../src/app/api/agents/[id]/route";
import * as r55 from "../../src/app/api/agents/[id]/jobs/route";
import * as r56 from "../../src/app/api/agents/[id]/jobs/[jobId]/route";
import * as r57 from "../../src/app/api/ai/render-md/route";
import * as r58 from "../../src/app/api/assets/[...path]/route";
import * as r59 from "../../src/app/api/auth/check/route";
import * as r60 from "../../src/app/api/auth/login/route";
import * as r61 from "../../src/app/api/browser/bookmarks/route";
import * as r62 from "../../src/app/api/browser/frame-check/route";
import * as r63 from "../../src/app/api/cabinets/classify/route";
import * as r64 from "../../src/app/api/cabinets/create/route";
import * as r65 from "../../src/app/api/cabinets/overview/route";
import * as r66 from "../../src/app/api/chat/channels/route";
import * as r67 from "../../src/app/api/chat/channels/[slug]/route";
import * as r68 from "../../src/app/api/cloud/status/route";
import * as r69 from "../../src/app/api/daemon/auth/route";
import * as r70 from "../../src/app/api/daemon/session/[id]/output/route";
import * as r71 from "../../src/app/api/daemon/sessions/route";
import * as r72 from "../../src/app/api/data-locations/route";
import * as r73 from "../../src/app/api/disclaimer/route";
import * as r74 from "../../src/app/api/git/commit/route";
import * as r75 from "../../src/app/api/git/diff/[hash]/route";
import * as r76 from "../../src/app/api/git/log/[...path]/route";
import * as r77 from "../../src/app/api/git/pull/route";
import * as r78 from "../../src/app/api/git/restore/route";
import * as r79 from "../../src/app/api/github/repo/route";
import * as r80 from "../../src/app/api/gmail/connect/route";
import * as r81 from "../../src/app/api/gmail/disconnect/route";
import * as r82 from "../../src/app/api/gmail/index/route";
import * as r83 from "../../src/app/api/gmail/search/route";
import * as r84 from "../../src/app/api/gmail/status/route";
import * as r85 from "../../src/app/api/gmail/thread/[id]/route";
import * as r86 from "../../src/app/api/google-drive/browse/route";
import * as r87 from "../../src/app/api/google-drive/mounts/route";
import * as r88 from "../../src/app/api/google-drive/mounts/[id]/route";
import * as r89 from "../../src/app/api/google-drive/reveal/route";
import * as r90 from "../../src/app/api/google-drive/serve/route";
import * as r91 from "../../src/app/api/google-drive/status/route";
import * as r92 from "../../src/app/api/google-drive/tree/route";
import * as r93 from "../../src/app/api/health/route";
import * as r94 from "../../src/app/api/health/daemon/route";
import * as r95 from "../../src/app/api/history/activity/route";
import * as r96 from "../../src/app/api/history/compact/route";
import * as r97 from "../../src/app/api/history/config/route";
import * as r98 from "../../src/app/api/history/diff/route";
import * as r99 from "../../src/app/api/history/file/route";
import * as r100 from "../../src/app/api/jobs/library/route";
import * as r101 from "../../src/app/api/kb/pages/meta/route";
import * as r102 from "../../src/app/api/knowledge-sources/connect-inline/route";
import * as r103 from "../../src/app/api/knowledge-sources/scan/route";
import * as r104 from "../../src/app/api/onboarding/setup/route";
import * as r105 from "../../src/app/api/pages/route";
import * as r106 from "../../src/app/api/pages/[...path]/route";
import * as r107 from "../../src/app/api/references/undo/route";
import * as r108 from "../../src/app/api/registry/route";
import * as r109 from "../../src/app/api/registry/import/route";
import * as r110 from "../../src/app/api/registry/[slug]/route";
import * as r111 from "../../src/app/api/rooms/route";
import * as r112 from "../../src/app/api/rooms/active/route";
import * as r113 from "../../src/app/api/schedule/parse/route";
import * as r114 from "../../src/app/api/search/route";
import * as r115 from "../../src/app/api/system/audit-log/route";
import * as r116 from "../../src/app/api/system/backup/route";
import * as r117 from "../../src/app/api/system/cabinet-manifest/route";
import * as r118 from "../../src/app/api/system/client-log/route";
import * as r119 from "../../src/app/api/system/create-file/route";
import * as r120 from "../../src/app/api/system/data-dir/route";
import * as r121 from "../../src/app/api/system/diagnostics/route";
import * as r122 from "../../src/app/api/system/diagnostics/export/route";
import * as r123 from "../../src/app/api/system/diagnostics/log-tail/route";
import * as r124 from "../../src/app/api/system/feedback/route";
import * as r125 from "../../src/app/api/system/file-settings/route";
import * as r126 from "../../src/app/api/system/import-apple-notes/route";
import * as r127 from "../../src/app/api/system/import-folder/route";
import * as r128 from "../../src/app/api/system/import-notion/route";
import * as r129 from "../../src/app/api/system/integration-requests/route";
import * as r130 from "../../src/app/api/system/link-repo/route";
import * as r131 from "../../src/app/api/system/open-data-dir/route";
import * as r132 from "../../src/app/api/system/open-path/route";
import * as r133 from "../../src/app/api/system/pick-directory/route";
import * as r134 from "../../src/app/api/system/pick-file/route";
import * as r135 from "../../src/app/api/system/restart/route";
import * as r136 from "../../src/app/api/system/reveal/route";
import * as r137 from "../../src/app/api/system/symlink/route";
import * as r138 from "../../src/app/api/system/update/route";
import * as r139 from "../../src/app/api/system/update/apply/route";
import * as r140 from "../../src/app/api/system/update/status/route";
import * as r141 from "../../src/app/api/telemetry/route";
import * as r142 from "../../src/app/api/telemetry/settings/route";
import * as r143 from "../../src/app/api/terminal/open/route";
import * as r144 from "../../src/app/api/tree/route";
import * as r145 from "../../src/app/api/upload/[...path]/route";
import * as r146 from "../../src/app/api/user/avatar/route";
import * as r147 from "../../src/app/api/user/profile/route";

export const apiRoutes = [
  { path: "/api/agents", methods: ["GET","POST"], module: r0 },
  { path: "/api/agents/auto-link", methods: ["POST"], module: r1 },
  { path: "/api/agents/channels", methods: ["GET","POST"], module: r2 },
  { path: "/api/agents/claude-login/:action", methods: ["GET","POST"], module: r3 },
  { path: "/api/agents/cli-proxy/*action", methods: ["GET","POST"], module: r4 },
  { path: "/api/agents/config", methods: ["GET","POST"], module: r5 },
  { path: "/api/agents/config/cabinet-env", methods: ["GET","PUT","DELETE"], module: r6 },
  { path: "/api/agents/config/cli-mcp-servers", methods: ["GET"], module: r7 },
  { path: "/api/agents/config/integration-environments", methods: ["GET","PUT"], module: r8 },
  { path: "/api/agents/config/integrations", methods: ["GET","PUT"], module: r9 },
  { path: "/api/agents/config/mcp-catalog", methods: ["GET"], module: r10 },
  { path: "/api/agents/config/mcp-catalog/connect", methods: ["POST","DELETE"], module: r11 },
  { path: "/api/agents/config/mcp-catalog/discord-check", methods: ["POST"], module: r12 },
  { path: "/api/agents/config/mcp-catalog/microsoft/login", methods: ["GET","POST","DELETE"], module: r13 },
  { path: "/api/agents/config/mcp-catalog/oauth/login", methods: ["GET","POST","DELETE"], module: r14 },
  { path: "/api/agents/config/mcp-catalog/test", methods: ["POST"], module: r15 },
  { path: "/api/agents/config/mcp-catalog/verify", methods: ["POST"], module: r16 },
  { path: "/api/agents/config/notifications/test", methods: ["POST"], module: r17 },
  { path: "/api/agents/conversations", methods: ["GET","POST"], module: r18 },
  { path: "/api/agents/conversations/events", methods: ["GET"], module: r19 },
  { path: "/api/agents/conversations/:id", methods: ["GET","PATCH","DELETE"], module: r20 },
  { path: "/api/agents/conversations/:id/actions", methods: ["GET","POST"], module: r21 },
  { path: "/api/agents/conversations/:id/claude-transcript", methods: ["GET"], module: r22 },
  { path: "/api/agents/conversations/:id/compact", methods: ["POST"], module: r23 },
  { path: "/api/agents/conversations/:id/continue", methods: ["POST"], module: r24 },
  { path: "/api/agents/conversations/:id/diffs", methods: ["GET"], module: r25 },
  { path: "/api/agents/conversations/:id/events", methods: ["GET"], module: r26 },
  { path: "/api/agents/conversations/:id/events-log", methods: ["GET"], module: r27 },
  { path: "/api/agents/digest", methods: ["POST"], module: r28 },
  { path: "/api/agents/events", methods: ["GET"], module: r29 },
  { path: "/api/agents/gallery", methods: ["GET"], module: r30 },
  { path: "/api/agents/headless", methods: ["POST"], module: r31 },
  { path: "/api/agents/import", methods: ["POST"], module: r32 },
  { path: "/api/agents/inbox-drafts", methods: ["GET","POST","DELETE"], module: r33 },
  { path: "/api/agents/library", methods: ["GET"], module: r34 },
  { path: "/api/agents/library/:slug/add", methods: ["POST"], module: r35 },
  { path: "/api/agents/personas", methods: ["GET","POST"], module: r36 },
  { path: "/api/agents/personas/:slug", methods: ["GET","PUT","DELETE"], module: r37 },
  { path: "/api/agents/personas/:slug/avatar", methods: ["GET","POST","DELETE"], module: r38 },
  { path: "/api/agents/personas/:slug/export", methods: ["GET"], module: r39 },
  { path: "/api/agents/personas/:slug/workspace", methods: ["GET"], module: r40 },
  { path: "/api/agents/providers", methods: ["GET","PUT"], module: r41 },
  { path: "/api/agents/providers/status", methods: ["GET"], module: r42 },
  { path: "/api/agents/providers/:id/models", methods: ["GET"], module: r43 },
  { path: "/api/agents/providers/:id/verify", methods: ["POST"], module: r44 },
  { path: "/api/agents/review", methods: ["POST"], module: r45 },
  { path: "/api/agents/scheduler", methods: ["GET","POST"], module: r46 },
  { path: "/api/agents/skills", methods: ["GET","POST"], module: r47 },
  { path: "/api/agents/skills/catalog", methods: ["GET"], module: r48 },
  { path: "/api/agents/skills/import", methods: ["POST"], module: r49 },
  { path: "/api/agents/skills/scan", methods: ["GET"], module: r50 },
  { path: "/api/agents/skills/:key", methods: ["GET","PATCH","DELETE"], module: r51 },
  { path: "/api/agents/skills/:key/bundle-into-cabinet", methods: ["POST"], module: r52 },
  { path: "/api/agents/tasks", methods: ["GET","POST"], module: r53 },
  { path: "/api/agents/:id", methods: ["GET","DELETE"], module: r54 },
  { path: "/api/agents/:id/jobs", methods: ["GET","POST"], module: r55 },
  { path: "/api/agents/:id/jobs/:jobId", methods: ["GET","PUT","DELETE"], module: r56 },
  { path: "/api/ai/render-md", methods: ["POST"], module: r57 },
  { path: "/api/assets/*path", methods: ["GET","PUT"], module: r58 },
  { path: "/api/auth/check", methods: ["GET"], module: r59 },
  { path: "/api/auth/login", methods: ["POST"], module: r60 },
  { path: "/api/browser/bookmarks", methods: ["GET","POST","PATCH","DELETE"], module: r61 },
  { path: "/api/browser/frame-check", methods: ["GET"], module: r62 },
  { path: "/api/cabinets/classify", methods: ["GET"], module: r63 },
  { path: "/api/cabinets/create", methods: ["POST"], module: r64 },
  { path: "/api/cabinets/overview", methods: ["GET"], module: r65 },
  { path: "/api/chat/channels", methods: ["GET","POST"], module: r66 },
  { path: "/api/chat/channels/:slug", methods: ["GET","POST"], module: r67 },
  { path: "/api/cloud/status", methods: ["GET"], module: r68 },
  { path: "/api/daemon/auth", methods: ["GET"], module: r69 },
  { path: "/api/daemon/session/:id/output", methods: ["GET"], module: r70 },
  { path: "/api/daemon/sessions", methods: ["GET"], module: r71 },
  { path: "/api/data-locations", methods: ["GET"], module: r72 },
  { path: "/api/disclaimer", methods: ["GET","POST"], module: r73 },
  { path: "/api/git/commit", methods: ["GET","POST"], module: r74 },
  { path: "/api/git/diff/:hash", methods: ["GET"], module: r75 },
  { path: "/api/git/log/*path", methods: ["GET"], module: r76 },
  { path: "/api/git/pull", methods: ["POST"], module: r77 },
  { path: "/api/git/restore", methods: ["POST"], module: r78 },
  { path: "/api/github/repo", methods: ["GET"], module: r79 },
  { path: "/api/gmail/connect", methods: ["POST"], module: r80 },
  { path: "/api/gmail/disconnect", methods: ["DELETE"], module: r81 },
  { path: "/api/gmail/index", methods: ["POST"], module: r82 },
  { path: "/api/gmail/search", methods: ["GET"], module: r83 },
  { path: "/api/gmail/status", methods: ["GET"], module: r84 },
  { path: "/api/gmail/thread/:id", methods: ["GET"], module: r85 },
  { path: "/api/google-drive/browse", methods: ["GET"], module: r86 },
  { path: "/api/google-drive/mounts", methods: ["GET","POST"], module: r87 },
  { path: "/api/google-drive/mounts/:id", methods: ["DELETE"], module: r88 },
  { path: "/api/google-drive/reveal", methods: ["POST"], module: r89 },
  { path: "/api/google-drive/serve", methods: ["GET"], module: r90 },
  { path: "/api/google-drive/status", methods: ["GET"], module: r91 },
  { path: "/api/google-drive/tree", methods: ["GET"], module: r92 },
  { path: "/api/health", methods: ["GET"], module: r93 },
  { path: "/api/health/daemon", methods: ["GET"], module: r94 },
  { path: "/api/history/activity", methods: ["GET"], module: r95 },
  { path: "/api/history/compact", methods: ["POST"], module: r96 },
  { path: "/api/history/config", methods: ["GET","PATCH"], module: r97 },
  { path: "/api/history/diff", methods: ["GET"], module: r98 },
  { path: "/api/history/file", methods: ["GET"], module: r99 },
  { path: "/api/jobs/library", methods: ["GET"], module: r100 },
  { path: "/api/kb/pages/meta", methods: ["POST"], module: r101 },
  { path: "/api/knowledge-sources/connect-inline", methods: ["POST"], module: r102 },
  { path: "/api/knowledge-sources/scan", methods: ["GET"], module: r103 },
  { path: "/api/onboarding/setup", methods: ["POST"], module: r104 },
  { path: "/api/pages", methods: ["GET","POST","PUT"], module: r105 },
  { path: "/api/pages/*path", methods: ["GET","POST","PUT","PATCH","DELETE"], module: r106 },
  { path: "/api/references/undo", methods: ["POST"], module: r107 },
  { path: "/api/registry", methods: ["GET"], module: r108 },
  { path: "/api/registry/import", methods: ["POST"], module: r109 },
  { path: "/api/registry/:slug", methods: ["GET"], module: r110 },
  { path: "/api/rooms", methods: ["GET","PATCH","DELETE"], module: r111 },
  { path: "/api/rooms/active", methods: ["POST"], module: r112 },
  { path: "/api/schedule/parse", methods: ["POST"], module: r113 },
  { path: "/api/search", methods: ["GET"], module: r114 },
  { path: "/api/system/audit-log", methods: ["POST"], module: r115 },
  { path: "/api/system/backup", methods: ["POST"], module: r116 },
  { path: "/api/system/cabinet-manifest", methods: ["GET"], module: r117 },
  { path: "/api/system/client-log", methods: ["POST"], module: r118 },
  { path: "/api/system/create-file", methods: ["POST"], module: r119 },
  { path: "/api/system/data-dir", methods: ["GET","PUT","DELETE"], module: r120 },
  { path: "/api/system/diagnostics", methods: ["GET","PATCH","DELETE"], module: r121 },
  { path: "/api/system/diagnostics/export", methods: ["GET"], module: r122 },
  { path: "/api/system/diagnostics/log-tail", methods: ["GET"], module: r123 },
  { path: "/api/system/feedback", methods: ["POST"], module: r124 },
  { path: "/api/system/file-settings", methods: ["POST"], module: r125 },
  { path: "/api/system/import-apple-notes", methods: ["POST"], module: r126 },
  { path: "/api/system/import-folder", methods: ["POST"], module: r127 },
  { path: "/api/system/import-notion", methods: ["POST"], module: r128 },
  { path: "/api/system/integration-requests", methods: ["POST"], module: r129 },
  { path: "/api/system/link-repo", methods: ["POST"], module: r130 },
  { path: "/api/system/open-data-dir", methods: ["POST"], module: r131 },
  { path: "/api/system/open-path", methods: ["POST"], module: r132 },
  { path: "/api/system/pick-directory", methods: ["POST"], module: r133 },
  { path: "/api/system/pick-file", methods: ["POST"], module: r134 },
  { path: "/api/system/restart", methods: ["POST"], module: r135 },
  { path: "/api/system/reveal", methods: ["POST"], module: r136 },
  { path: "/api/system/symlink", methods: ["GET","PATCH"], module: r137 },
  { path: "/api/system/update", methods: ["GET"], module: r138 },
  { path: "/api/system/update/apply", methods: ["POST"], module: r139 },
  { path: "/api/system/update/status", methods: ["GET"], module: r140 },
  { path: "/api/telemetry", methods: ["POST"], module: r141 },
  { path: "/api/telemetry/settings", methods: ["GET","POST"], module: r142 },
  { path: "/api/terminal/open", methods: ["POST"], module: r143 },
  { path: "/api/tree", methods: ["GET"], module: r144 },
  { path: "/api/upload/*path", methods: ["POST","PUT","DELETE"], module: r145 },
  { path: "/api/user/avatar", methods: ["GET","POST","DELETE"], module: r146 },
  { path: "/api/user/profile", methods: ["GET","PUT"], module: r147 },
] as const;
